### ISSUE TITLE
Weird lighting on Engineer's left viewmodel hand.

### ISSUE THREAD

**Issue by classicsonic2d** [tf2classic/tf2classic-issue-tracker#309] opened 2024-03-11 18:23 UTC
A bug where Engineer's left hand uses weird, and ugly dark lighting (seems to be a problem with the vmt)
What it looks like:
<img width="1280" alt="Screenshot 2024-03-11 142017" src="https://github.com/tf2classic/tf2classic-issue-tracker/assets/126111132/2d4656dc-b9ed-4a7c-8837-5c63837d7635">

What it should look like, with my own fixed vmt.

<img width="1280" alt="Screenshot 2024-03-11 141858" src="https://github.com/tf2classic/tf2classic-issue-tracker/assets/126111132/69f16604-e5a9-4573-bad1-790128f394b0">

**Comment by newgreenshoot** [comment] 2024-05-02 10:42
Can you explain what you changed in your VMT, exactly?

**Comment by newgreenshoot** [comment] 2024-08-05 11:16
Likely a dupe of #321.

**Closed as not planned by newgreenshoot** 2024-08-05 11:16 UTC
Labels: duplicate
