### ISSUE TITLE
Broken response rules for the Hunting Rifle

### ISSUE THREAD

**Issue by Hypnos2001** [tf2classic/tf2classic-issue-tracker#374] opened 2024-06-08 18:43 UTC
Whenever a sniper scopes in on an enemy player with the stock Sniper Rifle he has a rare chance to play a corresponding voice line.
However if the player is using the Hunting Rifle, he will _always_ play a voice line every single time he scopes in on another player.

https://github.com/tf2classic/tf2classic-issue-tracker/assets/82730926/8ae1dd31-94c1-4e3a-bcd0-4ad001aed32f

**Comment by newgreenshoot** [comment] 2024-08-05 11:15
I can't seem to reproduce this as described. The Hunting Revolver does play a response on every enemy scope, but stock does too, and that matches how it's supposed to work in the response rules. The response criteria for SniperHoldStill should equally apply to both weapons, since DeployedContext is just checking if TF_COND_ZOOMED is set, which it is in both cases.

If it was supposed to only happen sometimes, that would need to be set explicitly. There are other criteria that could be added, the base rules file includes 50PercentChance, 75PercentChance, etc. which are set for a lot of other rules, but not this one, so this seems deliberate. It'd be a bug if the stock rifle _didn't_ do this.

I'll close this for now, but if you have any more information, feel free to post and I'll reopen if there's something I missed.

**Closed as not planned by newgreenshoot** 2024-08-05 11:15 UTC
Labels: not a bug
